-- supabase/migrations/20260828010000_live_verification_events.sql
--
-- Real firing verification, as opposed to Preview mode's local simulation.
-- A business owner runs a short-lived snippet (generated by
-- LiveVerifyModal) in their own browser's console while on their actual
-- live site; it hooks window.dataLayer.push and reports each pushed event
-- back here via an anonymous, unauthenticated insert — there's no Supabase
-- session available on a third-party site, so the public anon key plus a
-- random per-check token is the whole access model, not auth.uid().
--
-- No display_id on this table, unlike every other domain table: this is
-- ephemeral capture data (many small rows per check), not a named entity a
-- user ever looks up by a human-readable ID.

create table if not exists public.live_verification_events (
  id                   uuid        primary key default gen_random_uuid(),
  check_token          uuid        not null,
  conversion_event_id  uuid        not null references public.conversion_events(id) on delete cascade,
  organisation_id      uuid        not null references public.organisations(id)     on delete cascade,
  event_name           text,
  event_payload        jsonb       not null,
  captured_at          timestamptz not null default now(),
  check (octet_length(event_payload::text) <= 4000)
);

create index if not exists live_verification_events_check_token_idx
  on public.live_verification_events (check_token);

create index if not exists live_verification_events_event_captured_idx
  on public.live_verification_events (conversion_event_id, captured_at);

alter table public.live_verification_events enable row level security;

-- No auth.uid() is available here — the insert comes from an anonymous
-- script running on the business owner's own site, authenticated only by
-- the public anon key. The one real guard: the row must reference a
-- conversion_event/organisation pair that actually exists together, so a
-- stray or guessed check_token can't attach fabricated rows to an
-- arbitrary org's data.
drop policy if exists "anonymous live checks can be recorded" on public.live_verification_events;
create policy "anonymous live checks can be recorded"
  on public.live_verification_events for insert
  with check (
    exists (
      select 1 from public.conversion_events ce
      where  ce.id              = live_verification_events.conversion_event_id
        and  ce.organisation_id = live_verification_events.organisation_id
        and  ce.deleted_at is null
    )
  );

drop policy if exists "members can view their org's live checks" on public.live_verification_events;
create policy "members can view their org's live checks"
  on public.live_verification_events for select
  using (is_active_org_member(organisation_id));
